### PR TITLE
Write alembic script to update current models to schema in branch pkg_table

### PR DESCRIPTION
**Pull request by charulagrl**
#39

### CODE REVIEW

**Comment by pypingou** [comment]
Couple of things about this pull-request, I normally do not use alembic to create table because then `createdb.py` works just fine, but that's not important.

What is more important is that with that third alembic script, all the data in the database is lost. After running it, there will be no way of knowing to which package(s) belong a file.
So the migration is not just about dropping the column but it will be first about moving it from the one table we made to the new tables, then dropping the columns.

**Comment by charulagrl** [comment]
@pypingou That makes sense. Can you tell me how can I do that ?

**Comment by pypingou** [comment]
I guess you will have to do some select and insert queries in the script :)

**Comment by ralphbean** [comment]
@charulagrl, here's an example of another upgrade script that doesn't do exactly what you need it to, but it does show how to do queries:  https://github.com/fedora-infra/datanommer/blob/develop/datanommer.models/alembic/versions/a4f74590bcf_determine_category.py#L37-L67

**Comment by ralphbean** [comment]
@charulagrl any progress on this?  Anything I can help with?

**Comment by charulagrl** [comment]
@ralphbean Thanks for asking. I had done some other small fixes in the code and didn't look much into it. Will try doing it this weekend.

**Comment by ralphbean** [comment]
OK, we haven't heard back on this so I'm going to close it.  Please resubmit if there's ongoing work.

**Pull request closed without merging**
