### PR TITLE
Alembic migration script to sync models with new schema in branch pkg_table

### PR DESCRIPTION
**Pull request by charulagrl**
#38

### CODE REVIEW

**Comment by pypingou** [comment]
Something is odd here, there are commits from @ralphbean but none of the commits from the pkg_table branch that this pull-request is supposed to enhanced (while the changes have not been merged yet).

**Comment by charulagrl** [comment]
@pypingou Yes I agree. Should i delete this pull request and try creating a new one ?

**Comment by pypingou** [comment]
@charulagrl you should be able to fix this without closing this pull-request and opening a new one, rebase your branch on the top of mine and force push to your clone

**Comment by charulagrl** [comment]
After rebase also, it was showing above commit as its head. I am closing this pull request for now and open a new one.

**Pull request closed without merging**
