### PR TITLE
replaced optparse with argparse

### PR DESCRIPTION
**Pull request by charulagrl**
issue #29

### CODE REVIEW

**Comment by charulagrl** [comment]
@pypingou @ralphbean  I have gone through several CLI library and found python-cliff would be a better option for summershum project. 
it is because
        1. Cliff is built on the top of argparse
        2. interactive console
        3. auto completion
        4. command listing
        5. different output format like csv, json etc
        6. repl support, we can add programming construct in future i.e. loop, condition etc, to remove redundant tasks. For e.g. if we want five messages to get stored in one time 

<pre>
[charul@localhost] summershum
(summershum) --version   (interactive) 
(summershum) list commands -f csv
(summershum) store -loop=5 --id=[messaged id list] (storing 5 message)
</pre>

I have build a sample cli app using it and its pretty cool. I am waiting for your views on this.

**Comment by ralphbean** [comment]
:+1: here.  @pypingou?

**Comment by ralphbean** [comment]
On "cliff", it is very nice; I use it for the "pkgwat" tool.  However, I think it might be overkill here.  
Summershum has only one real command (no subcommands) and only two options.  Argparse is more than sufficient.

**Comment by ralphbean** [comment]
Although, `store --loop=5` is a pretty neat idea.

**Comment by pypingou** [comment]
:+1: for me as well on the pr

cliff is nice but I also think it's overkill/over-engineering for summershum-cli, we should be able to add the `--loop` option w/o cliff :)

**Comment by ralphbean** [comment]
Thanks for the patch, @charulagrl!

**Pull request merged**
